[gen-reconnect-during-error.https.html]
  [disconnect() and connect() called during a getPrimaryService call that fails. Reject with NetworkError.]
    expected: FAIL
