[gen-reconnect-during-success.https.html]
  [disconnect() and connect() called during a getPrimaryService call that succeeds. Reject with NetworkError.]
    expected: FAIL
